#!/usr/bin/env python
"""
    jlddebouncer

    @author: Jean-Lou Dupont
"""
__version__="0.2"
import os, sys, argparse
op=os.path

try:
    import jlddk #@UnusedImport
except:
    ### must be in dev mode then    
    this_dir=op.dirname(__file__)
    lib_path=op.abspath(op.join(this_dir, ".."))
    sys.path.insert(0, lib_path)
    import jlddk #@UnusedImport

########################################################################

DESC="Debounces changes in {key:value} pairs (JSON output) - v%s" % __version__
DEFAULTS={
          "hin": 3
          ,"timeout": 30
          ,"polling_interval": 30
          }

def main():
    try:
        import jlddk.do_setup #@UnusedImport
        import logging
        import jlddk.do_checks #@UnusedImport
        
        parser=argparse.ArgumentParser(description=DESC, fromfile_prefix_chars='@', formatter_class=argparse.RawTextHelpFormatter)
        parser.add_argument('-key',   dest='key',    type=str, help="Key field name", required=True)
        parser.add_argument('-value', dest='value',  type=str, help="Value field name", required=True)        
        parser.add_argument('-itp',   dest='itopic',  type=str, help="Input topic of JSON message", required=True)
        parser.add_argument('-otp',   dest='otopic',  type=str, help="Output topic of JSON message", required=True)
        
        parser.add_argument('-ukv',   dest='use_kv', action="store_true", help="Use the input message's key & value field names", default=False)
        parser.add_argument('-hin',   dest='hin',    type=int, help="Input hysteresis (cycle)", default=DEFAULTS["hin"])
        
        parser.add_argument('-p',   dest="polling_interval", type=int,  help="Polling interval", default=DEFAULTS["polling_interval"])
        parser.add_argument('-to',  dest="timeout",          type=int,  help="{key:value} stale timeout (cycle)", default=DEFAULTS["timeout"])
        
        from jlddk.script_debouncer import run
        from jlddk.tools_sys import process_command_line
        args=process_command_line(parser)
        run(**args)

    except KeyboardInterrupt:
        logging.info("..Exiting")
        sys.exit(0)##no probs
        
    except Exception,e:
        logging.error(str(e))
        sys.exit(1)
        
sys.exit(main())
