#!/usr/bin/env python
"""
    jldfcomp - compare globs of files

    @author: Jean-Lou Dupont
"""
import os, sys, argparse
op=os.path

try:
    import jlddk
except:
    ### must be in dev mode then    
    this_dir=op.dirname(__file__)
    lib_path=op.abspath(op.join(this_dir, ".."))
    sys.path.insert(0, lib_path)
    import jlddk

########################################################################

DESC="Compare globs of files"
DEFAULTS={
          }

def main():
    try:
        import jlddk.do_setup
        import logging
        import jlddk.do_checks
        from jlddk.tools_sys import info_dump, dnorm
        
        parser=argparse.ArgumentParser(description=DESC, fromfile_prefix_chars='@')
        
        parser.add_argument('-lm',  dest='list_matches',  action="store_true", help="List matches")
        parser.add_argument('-ld',  dest='list_diffs',    action="store_true", help="List differences")
        parser.add_argument('-ls',  dest='list_sets',     action="store_true", help="List working sets")
        
        parser.add_argument('-jbn', dest='just_basename', action="store_true", help="Just basename comparison")
        parser.add_argument('-jfn', dest='just_filename', action="store_true", help="Just filename (no extension)")
        
        parser.add_argument('-vb',  dest='verbose', action="store_true", help="Verbose output")
        
        parser.add_argument('-pa',  dest='path_a',  type=str, help="Path 'a'", required=True)
        parser.add_argument('-pb',  dest='path_b',  type=str, help="Path 'b'", required=True)
                        
        args=parser.parse_args()
        
        #info_dump(vars(args), 20)
        
        from jlddk.script_fcomp import run
        run(**dnorm(vars(args)))

    except KeyboardInterrupt:
        logging.info("..Exiting")
        sys.exit(0)##no probs
        
    except Exception,e:
        logging.error(str(e))
        sys.exit(1)
        
sys.exit(main())
