#!/usr/bin/env python
"""
    jldwebdl - download pages to a directory, output results to stdout using JSON

    @author: Jean-Lou Dupont
"""
__version__="0.2"
import os, sys, argparse
op=os.path

try:
    import jlddk #@UnusedImport
except:
    ### must be in dev mode then    
    this_dir=op.dirname(__file__)
    lib_path=op.abspath(op.join(this_dir, ".."))
    sys.path.insert(0, lib_path)
    import jlddk #@UnusedImport

########################################################################

DESC="""Download web pages - v%s""" % __version__
DEFAULTS={
          "polling_interval": 30
          ,"batch_size": 5
          }

def main():
    try:
        import jlddk.do_setup  #@UnusedImport
        import logging
        import jlddk.do_checks #@UnusedImport
        
        parser=argparse.ArgumentParser(description=DESC, fromfile_prefix_chars='@', formatter_class=argparse.RawTextHelpFormatter)
        parser.add_argument('-sp',  dest='source_path',  type=str, help="Source path", required=True)
        parser.add_argument('-dp',  dest='dest_path',    type=str, help="Destination path", required=True)
        parser.add_argument('-cp',  dest='check_path',    type=str, help="Check path")
        
        parser.add_argument('-dfe', dest="delete_fetch_error", action="store_true", help="Delete source file if url can't be fetched", default=False)
        
        parser.add_argument('-p',  dest="polling_interval", type=int, action="store", help="Polling interval (seconds)", default=DEFAULTS["polling_interval"])
        parser.add_argument('-bs', dest="batch_size", type=int, action="store", help="Maximum batch size per polling interval", default=DEFAULTS["batch_size"])
        
        from jlddk.script_webdl import run
        from jlddk.tools_sys import process_command_line
        args=process_command_line(parser)
        run(**args)

    except KeyboardInterrupt:
        logging.info("..Exiting")
        sys.exit(0)##no probs
        
    except Exception,e:
        logging.error(str(e))
        sys.exit(1)
        
sys.exit(main())
